"""
agents/pr_agent.py
──────────────────
PR Agent: creates a GitHub branch, commits all generated files,
and opens a Pull Request for human review.
"""
from __future__ import annotations

import base64
import logging
import os
import autogen
from pathlib import Path

from agents.base_agent import PhantomBaseAgent, WORKSPACE
from orchestrator.state import TaskState, TaskStatus

logger = logging.getLogger(__name__)

PR_SYSTEM_PROMPT = """
You are the PR Agent in PhantomDev.

YOUR JOB:
1. Call create_pull_request() to push all generated code and open a PR.
2. Report the PR URL to the team.
3. Emit the human approval signal.

End your message with EXACTLY this line (required to stop the pipeline):
"HUMAN_APPROVAL_REQUIRED: PR is ready for review at <url>"

Available tool:
  create_pull_request() -> str  (returns JSON with pr_url and pr_number)
"""


def build_pr_agent(llm_config: dict, state: TaskState) -> autogen.ConversableAgent:
    agent = autogen.ConversableAgent(
        name="PRAgent",
        system_message="You are the PR Agent.",
        llm_config=False,  # Disable LLM entirely for this deterministic step
        human_input_mode="NEVER",
    )

    def generate_pr_reply(agent, messages, sender, config):
        import json
        result_json = _create_pr(state)
        res = json.loads(result_json)
        
        if res.get("status") in ("success", "dry_run"):
            url = res.get("pr_url")
            msg = f"```json\n{result_json}\n```\n\nHUMAN_APPROVAL_REQUIRED: PR is ready for review at {url}"
            return True, msg
        else:
            return True, f"PHANTOMDEV_FAILED: PR creation failed: {res.get('message')}"

    agent.register_reply([autogen.Agent, None], generate_pr_reply, position=0)
    return agent


def _create_pr(state: TaskState) -> str:
    """
    Push all workspace files to GitHub and open a PR.
    Falls back to a dry-run report if GITHUB_TOKEN is not set.
    """
    import json
    token = os.getenv("GITHUB_TOKEN", "")
    repo_name = state.target_repo or os.getenv("TARGET_REPO", "")

    # Ignore the default .env placeholder
    if repo_name == "your_username/your_repo":
        repo_name = ""

    if not token or not repo_name:
        # Dry-run mode — no GitHub token configured
        dry_run_summary = _dry_run_summary(state)
        state.pr_url = "http://localhost:3000/dry-run"
        state.branch_name = f"phantomdev/task-{state.task_id[:8]}"
        state.set_status(TaskStatus.PR_OPEN)
        state.add_message("PRAgent", f"✅ DRY RUN: {dry_run_summary}")
        return json.dumps({
            "status": "dry_run",
            "message": dry_run_summary,
            "pr_url": state.pr_url,
            "files_count": len(state.generated_files) + len(state.test_files),
        })

    try:
        from github import Github, GithubException

        g = Github(token)
        repo = g.get_repo(repo_name)

        # Create branch
        branch_name = f"phantomdev/issue-{state.github_issue_number}-{state.task_id[:6]}"
        state.branch_name = branch_name

        base_ref = repo.get_branch(state.base_branch)
        try:
            repo.create_git_ref(
                ref=f"refs/heads/{branch_name}",
                sha=base_ref.commit.sha
            )
            logger.info(f"Created branch: {branch_name}")
        except GithubException as e:
            if e.status == 422:
                logger.warning(f"Branch already exists: {branch_name}")
            else:
                raise

        # Commit all generated files
        all_files = {**state.generated_files, **state.test_files}
        commit_message = (
            f"feat: PhantomDev implementation for issue #{state.github_issue_number}\n\n"
            f"Auto-generated by PhantomDev | Task: {state.task_id}\n"
            f"Coverage: {state.metrics.coverage_pct:.0f}% | "
            f"Tests: {state.metrics.test_pass_rate:.0f}% pass rate"
        )

        for file_path, content in all_files.items():
            try:
                encoded = base64.b64encode(content.encode()).decode()
                try:
                    existing = repo.get_contents(file_path, ref=branch_name)
                    repo.update_file(
                        file_path, f"update {file_path}", content,
                        existing.sha, branch=branch_name
                    )
                except GithubException:
                    repo.create_file(
                        file_path, f"add {file_path}", content,
                        branch=branch_name
                    )
                logger.info(f"Committed: {file_path}")
            except Exception as e:
                logger.error(f"Failed to commit {file_path}: {e}")

        # Build PR body
        pr_body = state.pr_body or _default_pr_body(state)

        # Create PR
        pr = repo.create_pull(
            title=f"[PhantomDev] {state.github_issue_title}",
            body=pr_body,
            head=branch_name,
            base=state.base_branch,
        )

        # Link to original issue
        if state.github_issue_number:
            issue = repo.get_issue(state.github_issue_number)
            issue.create_comment(
                f"🤖 PhantomDev has opened PR #{pr.number} for this issue: {pr.html_url}"
            )

        state.pr_url = pr.html_url
        state.pr_number = pr.number
        state.set_status(TaskStatus.PR_OPEN)
        state.add_message("PRAgent", f"✅ PR created: {pr.html_url}")

        return json.dumps({
            "status": "success",
            "pr_url": pr.html_url,
            "pr_number": pr.number,
            "branch": branch_name,
            "files_committed": len(all_files),
        })

    except ImportError:
        return json.dumps({"status": "error", "message": "PyGithub not installed. Run: pip install PyGithub"})
    except Exception as e:
        logger.error(f"PR creation failed: {e}")
        state.fail(f"PR creation error: {e}")
        return json.dumps({"status": "error", "message": str(e)})


def _dry_run_summary(state: TaskState) -> str:
    files = list(state.generated_files.keys()) + list(state.test_files.keys())
    return (
        f"Would create branch phantomdev/task-{state.task_id[:8]}, "
        f"commit {len(files)} files, open PR. "
        f"Set GITHUB_TOKEN + TARGET_REPO in .env to enable real GitHub integration. "
        f"Files: {', '.join(files[:5])}{'...' if len(files) > 5 else ''}"
    )


def _default_pr_body(state: TaskState) -> str:
    files_list = "\n".join(f"- `{p}`" for p in list(state.generated_files.keys())[:20])
    findings = "\n".join(
        f"- [{f.severity}] {f.test_id}: {f.issue_text[:80]} ({f.filename}:{f.line_number})"
        for f in state.security_findings[:10]
    ) or "None"

    return f"""
## Summary
This PR implements the requirements from issue #{state.github_issue_number}: **{state.github_issue_title}**

Auto-generated by [PhantomDev](https://github.com/phantomdev) | Task ID: `{state.task_id}`

## Changes
{files_list}

## Requirements Implemented
{chr(10).join(f"- {r}" for r in state.requirements)}

## Acceptance Criteria
{chr(10).join(f"- [ ] {c}" for c in state.acceptance_criteria)}

## Testing
- Test pass rate: **{state.metrics.test_pass_rate * 100:.0f}%**
- Code coverage: **{state.metrics.coverage_pct:.0f}%**

## Security
{findings}

## Checklist
- [ ] Code reviewed by human engineer
- [ ] Tests pass locally
- [ ] No regression in existing tests
- [ ] Documentation updated
""".strip()
